/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.*/
function fibEvensSum(stopPoint) {
  const arr = [1, 2];
  let next = arr[0] + arr[1];
  let count = 2;
  while(next <= stopPoint) {
    arr[0] = arr[1];
    arr[1] = next;
    next = arr[0] + arr[1];
    if (next > stopPoint) break;
    if (next % 2 === 0) count += next; 
  }
  return count;
}

console.log(fibEvensSum(4000000));
console.log(fibEvensSum(60));