package problems;
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.*/
public class Problem2 {
	
	public long fibEvensSum(int stopPoint) {
		long[] arr = new long[] {1, 2};
		long next = arr[0] + arr[1];
		long count = 2;
		while(next <= stopPoint) {
			System.out.println(next);
			arr[0] = arr[1];
			arr[1] = next;
			next = arr[0] + arr[1];
			if (next > stopPoint) break;
			if (next % 2 == 0) count += next;
		}
		return count;
	}
	
}
